source 'https://rubygems.org'
gem 'pry'
gem 'eventmachine'
gem 'connection_pool', '~> 2.0.0'
gem 'jdbc-mysql'
gem 'redis', '~> 3.0.1'
gem 'hiredis', '~> 0.4.5'
gem 'json'
gem 'thread_safe'
gem 'jrjackson'
gem 'concurrent-ruby'
gem 'dotenv'
gem 'msgpack-jruby'
gem 'timers', '~> 4.0.1'