source 'https://rubygems.org'
gem 'pry'
gem 'eventmachine'
gem 'connection_pool', '~> 2.0.0'
gem 'jdbc-mysql'
gem 'redis', '~> 3.0.1'
gem 'hiredis', '~> 0.4.5'
gem 'json'
gem "hamster", "~> 1.0",  :git => 'https://github.com/hamstergem/hamster.git'
gem 'thread_safe'
gem 'jrjackson'
gem 'concurrent-ruby'
gem 'dotenv'
