# REQUESTS
module Receive
  LOGIN = :ln
  GAME_DATA = :gd
  HARVESTING = :hg


  NEW_BATTLE = :nb
  BATTLE_START = :bs
  # LOBBY_DATA = :ld
  SPAWN_UNIT = :su
  UNIT_PRODUCTION_TASK = :upt
  CAST_SPELL = :cs
  RESPONSE_BATTLE_INVITE = :rbi
  PING = :pg

  CONSTUCT_BUILDING = :cb
  CONSTUCT_UNIT = :cu

  UPDATE_LOBBY_DATA = :uld

  INVITE_OPPONENT_TO_BATTLE = :iotb
  RESPONSE_INVITATION_TO_BATTLE = :ritb
end
#RESPONSE
module Send
  AUTHORISED = :ad
  GAME_DATA = :gd
  PONG = :png
  GOLD_STORAGE_CAPACITY = :gsc
  NOTIFICATION = :ntct

  BUILDING_SYNC = :bsc

  SCORE_SYNC = :scs
  MANA_SYNC = :mns

  START_GAME_SCENE = :sgs

  SYNC_UNITS = :su

  UPDATE_LOBBY_DATA = :uld

  INVITE_TO_BATTLE = :itb
  CANCEL_INVITE = :ci
end
